### ISSUE TITLE
can't get some values from ECMWF tf.bufr

### ISSUE THREAD

**Issue by DaiDai-Dad** [ecmwf/pdbufr#69]
### What happened?

I have download the .bufr from https://data.ecmwf.int/forecasts/20230905/00z/0p4-beta/oper/, I want get [time, lat, lon, windspeed, pressure] about "13W", then I try this:
`pdbufr.read_bufr(bufrFp, 
    columns=("stormIdentifier", "timePeriod", "latitude", "longitude", "windSpeedAt10M", "pressureReducedToMeanSeaLevel", 
            ),
    filters={"stormIdentifier": "13W", },
   )`
but I get an empty dataframe
then I delete "timePeriod" and "windSpeedAt10M" from columns above, it can get 20 rows:
`   stormIdentifier  latitude  longitude  pressureReducedToMeanSeaLevel

0              13W      23.4      116.8                        99900.0
1              13W      23.5      117.0                       100000.0
2              13W      23.5      116.1                       100200.0
3              13W      22.8      115.2                       100300.0
4              13W      23.4      114.6                       100500.0
5              13W      23.4      114.5                       100300.0
6              13W      23.5      112.9                       100500.0
7              13W       NaN        NaN                            NaN
8              13W       NaN        NaN                            NaN
9              13W      24.0      112.0                       100400.0
10             13W      23.6      111.7                       100400.0
11             13W      24.0      109.8                       100500.0
12             13W      24.0      109.8                       100500.0
13             13W      23.9      109.4                       100400.0
14             13W      23.6      107.0                       100400.0
15             13W       NaN        NaN                            NaN
16             13W      24.4      108.6                       100500.0
17             13W      23.7      106.9                       100300.0
18             13W      23.7      107.0                       100300.0
19             13W      23.7      106.9                       100400.0`

then I delete "pressureReducedToMeanSeaLevel" from columns like this:
`pdbufr.read_bufr(bufrFp, 
    columns=("stormIdentifier", "latitude", "longitude"), 
    filters={"stormIdentifier": "13W", },
   )`
I got 40 rows:
`   stormIdentifier  latitude  longitude

0              13W      23.5      117.3
1              13W      23.4      116.8
2              13W      23.4      119.9
3              13W      23.5      117.0
4              13W      25.3      121.1
5              13W      23.5      116.1
6              13W      25.5      120.5
7              13W      22.8      115.2
8              13W      22.8      116.7
9              13W      23.4      114.6
10             13W      19.4      116.8
11             13W      23.4      114.5
12             13W      20.1      113.3
13             13W      23.5      112.9
14             13W      20.8      115.4
15             13W       NaN        NaN
16             13W       NaN        NaN
17             13W       NaN        NaN
18             13W       NaN        NaN
19             13W      24.0      112.0
20             13W      26.2      111.4
21             13W      23.6      111.7
22             13W      22.4      113.7
23             13W      24.0      109.8
24             13W      19.9      111.4
25             13W      24.0      109.8
26             13W      20.0      109.3
27             13W      23.9      109.4
28             13W      22.4      113.7
29             13W      23.6      107.0
30             13W      20.8      110.6
31             13W       NaN        NaN
32             13W       NaN        NaN
33             13W      24.4      108.6
34             13W      21.3      109.5
35             13W      23.7      106.9
36             13W      19.5      108.6
37             13W      23.7      107.0
38             13W      20.0      108.2
39             13W      23.7      106.9
40             13W      19.7      107.9`

oh, no, why this?
I use eccodes.codes_dump() get a json file, but I can't understand the structure because it's nested multilevel. I can found 31 "timePeriod" in the json by ctrl-f, why can't I get it in the 1st case above? If some row don't have "timePeriod", why not the value is NaN? All in all, why I got different rows within different columns and same filter?

some files are here:
[https://github.com/DaiDai-Dad/temp/blob/main/20230905000000-240h-oper-tf.bufr](url)
[https://github.com/DaiDai-Dad/temp/blob/main/output.json](url)

### What are the steps to reproduce the bug?

see above

### Version

0.11.0

### Platform (OS and architecture)

Windows10

**Comment by sandorkertesz** [comment]
Thank you for reporting this issue. Please consider the followings.

BUFR, as a message is flat, but has a hierarchical (tree) structure. The standard says:
![image](https://github.com/ecmwf/pdbufr/assets/9033020/739a683d-e814-4b4f-b4de-e6e814f7fcd4)
This means that each "coordinate descriptor" element introduces a new level in the hierarchy. `bufr_dump` can reveal this structure for you, but it is not easy to understand what you get. I personally use tools like  [CodesUI](https://confluence.ecmwf.int/display/METV/CodesUI) or [Metview](https://metview.readthedocs.io/), which provide graphical user interfaces to inspect the hierarchy. 

Now look at the first values of the elements you want to collect from the tree in file `20230905000000-240h-oper-tf.bufr`. I took this snapshot with CodesUI (in this tree some nodes with no siblings are not indented, so the structure is simpler than the bufr_dump) :

![image](https://github.com/ecmwf/pdbufr/assets/9033020/ddf44c5f-a51a-4aeb-8ac0-82c9f9f5777f)

CodesUI reveals these values:

timePeriod: 6
windSpeedAt10M: 9.8
pressureReducedToMeanSeaLevel: 1000400

Let us look at the tree branches they are located in. In bracket you can see the coordinate descriptor, its first 2 numbers define the "class", remember if "class" < 10 we get a new node in the tree. The elements you want to extract are located under the following tree branches.

"timePeriod" and "windSpeedAt10M":

```
  |- stromIndetifier: 11E [01025]
    ...
       |- hour: 0 [04004]
          |- minute: 0 [04005]
             ...
             |- meteorologicalAttributeSignificance: 3 [08005]
                |- latitude: 14.3 [05002]
                   |- longitude: -105.6 [06002]
                       |- windSpeedAt10M: 9.8  [11012]
                       ...
                       |- bearingOrAzimuth: 0 [05021]
                          |- timeSignificance: 1 [08021]
                              |- timePeriod: 6 [04024]
```

"pressureReducedToMeanSeaLevel":

```
|- stromIndetifier: 11E [01025]
    ...
      |- hour: 0 [04004]
          |- minute: 0 [04005]
             ... 
             |- meteorologicalAttributeSignificance: 5 [08005]
                 |- latitude: 12.4 [05002]
                    |- longitude: -105.9  [06002]
                        |- pressureReducedToMeanSeaLevel: 1000400 [10051]
```

Now you can see that "windSpeedAt10M" and "pressureReducedToMeanSeaLevel" are in completely different branches under different latitude and logitude values. `pdbufr` cannot collect them together.  However, as you noticed you can use: 

```python
columns=("stormIdentifier", "timePeriod", "latitude", "longitude", "windSpeedAt10M",),
```
and it works. However, because "timePeriod" and "pressureReducedToMeanSeaLevel" are in completely different branches under different latitude and logitude values this query would result in an empty dataframe:

```python
columns=("stormIdentifier", "timePeriod", "latitude", "longitude", "pressureReducedToMeanSeaLevel",),
```
Your other questions can all be answered by inspecting the tree. 

Unfortunately, this message has a very complicated structure and some combinations of the values simply cannot be extracted by the collector algorithm in pdbufr. In my opinion the message structure is simply wrong because if we follow the standard simply no "timePeriod" can be associated with "pressureReducedToMeanSeaLevel", which probably was not the intention of the data producer.

**Comment by sandorkertesz** [comment]
Further complications. 
Having inspected the whole message structure I can conclude that although we have this hierarchy:

```
|- stromIndetifier: 11E [01025]
    ...
       |- hour: 0 [04004]
          |- minute: 0 [04005]
             ...
             |- meteorologicalAttributeSignificance: 3 [08005]
                |- latitude: 14.3 [05002]
                   |- longitude: -105.6 [06002]
                       |- windSpeedAt10M: 9.8  [11012]
                       ...
                       |- bearingOrAzimuth: 0 [05021]
                          |- timeSignificance: 1 [08021]
                              |- timePeriod: 6 [04024]
```

`timePeriod=6` was meant to refer for the next `windSpeedAt10M` value!!! No generic bufr filter will ever guess it! Again, in my view this message structure is wrong.

**Comment by DaiDai-Dad** [comment]
Thank you for your reply. With your guidance, I have resolved this issue.

It has been proven that your conclusion is correct. This bufr file is not suitable for reading with pdbufr, as it is nested layer by layer and not a typical phenotype structure.

The method I used is this url（ https://confluence.ecmwf.int/display/ECC/bufr_read_tropical_cyclone ）, as can be seen from this scheme, the data is indeed nested layer by layer (reading each data requires looping and adding ranks). I don't know why the data builder operates this way.
